# @esphome-device
# ESP Entrada Configuration

substitutions:
  device_id: "0"
  open_duration: "29" # Tiempo para subir (segundos)
  close_duration: "28" # Tiempo para bajar (segundos)

esphome:
  name: esp-entrada

packages:
  common: !include common.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  output_power: 20.0dB

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: "platano+1234"
    ssid: "AP-Esp-Entrada"

switch:
  - platform: gpio
    pin: GPIO16
    id: relay_luz_techo_entrada
    restore_mode: ALWAYS_OFF
    name: "Luz Techo Entrada"

  - platform: gpio
    pin: GPIO17
    id: relay_luz_techo_lavadero
    restore_mode: ALWAYS_OFF
    name: "Luz Techo Lavadero"

  - platform: gpio
    pin: GPIO18
    id: relay_luz_exterior_lavadero
    restore_mode: ALWAYS_OFF
    inverted: True
    name: "Luz Exterior Lavadero"

  - platform: gpio
    pin: GPIO19
    id: relay_luz_exterior_vivienda
    restore_mode: ALWAYS_OFF
    inverted: True
    name: "Luz Exterior Vivienda"

  - platform: gpio
    pin: GPIO21
    id: relay_luz_cuadro_entrada
    restore_mode: ALWAYS_OFF
    inverted: True
    name: "Luz Cuadro Entrada"

  - platform: gpio
    pin: GPIO22
    id: relay_luz_mamposteria_entrada
    restore_mode: ALWAYS_OFF
    inverted: True
    name: "Luz Mamposteria Entrada"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO27
      mode:
        input: true
        pulldown: true
    id: button_entrada_2
    name: "Botón entrada 2"
    on_press:
      - switch.toggle: relay_luz_techo_entrada

  - platform: gpio
    pin:
      number: GPIO33
      mode:
        input: true
        pulldown: true
    id: button_lavadero_1
    name: "Botón lavadero 1"
    on_press:
      - switch.toggle: relay_luz_techo_lavadero
  - platform: gpio
    pin:
      number: GPIO26
      mode:
        input: true
        pulldown: true
    id: button_lavadero_2
    name: "Botón lavadero 2"
    on_press:
      - switch.toggle: relay_luz_exterior_lavadero
  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pulldown: true
    id: button_lavadero_3
    name: "Botón lavadero 3"
    on_press:
      - switch.toggle: relay_luz_exterior_vivienda
  - platform: gpio
    pin:
      number: GPIO13
      mode:
        input: true
        pulldown: true
    id: button_entrada_1
    name: "Botón entrada 1"
    on_press:
      - switch.toggle: relay_luz_cuadro_entrada
