# @esphome-device
# Cocina Configuration

esphome:
  name: esp-cocina

packages:
  common: !include common.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  output_power: 20.0dB

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: "platano+1234"
    ssid: "AP-Cocina"

switch:
  - platform: gpio
    pin: GPIO19
    id: relay_light_barra_cocina
    restore_mode: ALWAYS_OFF
    inverted: True
    name: "Luz Barra Cocina"
  - platform: gpio
    pin: GPIO21
    id: relay_light_isla_cocina
    restore_mode: ALWAYS_OFF
    inverted: True
    name: "Luz Isla Cocina"
  - platform: gpio
    pin: GPIO22
    id: relay_light_techo_cocina
    restore_mode: ALWAYS_OFF
    inverted: True
    name: "Luz Techo Cocina"

script:
  - id: toggle_light_barra_cocina
    then:
      - switch.turn_on: relay_light_barra_cocina
      - delay: 300ms
      - switch.turn_off: relay_light_barra_cocina

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO33
      mode:
        input: true
        pulldown: true
    id: boton_1_jung_exteriores
    name: "Botón 1 Jung Exteriores"
  - platform: gpio
    pin:
      number: GPIO32
      mode:
        input: true
        pulldown: true
    id: boton_2_jung_exteriores
    name: "Botón 2 Jung Exteriores"
  - platform: gpio
    pin:
      number: GPIO27
      mode:
        input: true
        pulldown: true
    id: boton_3_jung_exteriores
    name: "Botón 3 Jung Exteriores"
  - platform: gpio
    pin:
      number: GPIO26
      mode:
        input: true
        pulldown: true
    id: boton_4_jung_exteriores
    name: "Botón 4 Jung Exteriores"
  - platform: gpio
    pin:
      number: GPIO25
      mode:
        input: true
        pulldown: true
    id: boton_5_jung_exteriores
    name: "Botón 5 Jung Exteriores"
  - platform: gpio
    pin:
      number: GPIO15
      mode:
        input: true
        pulldown: true
    id: boton_6_jung_exteriores
    name: "Botón 6 Jung Exteriores"
  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pulldown: true
    id: boton_7_jung_exteriores
    name: "Botón 7 Jung Exteriores"
  - platform: gpio
    pin:
      number: GPIO13
      mode:
        input: true
        pulldown: true
    id: boton_8_jung_exteriores
    name: "Botón 8 Jung Exteriores"
