# @esphome-device
# Persiana Oficina 1 Configuration

substitutions:
  device_id: "0"
  open_duration: "29" # Tiempo para subir (segundos)
  close_duration: "28" # Tiempo para bajar (segundos)

esphome:
  name: persiana-oficina-1

packages:
  base: !include persiana-base.yaml
  oficina_base: !include persiana-oficina-base.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  output_power: 20.0dB

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: "platano+1234"
    ssid: "AP-Persiana-Oficina-1"
