# Persiana Dormitorio 2 Configuration
# Imports shared logic from persiana-base.yaml

esphome:
  name: persiana-dormitorio-2

<<: !include persiana-base.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  output_power: 20.0dB

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: "platano+1234"
    ssid: "AP-Persiana-Dormitorio-2"

  manual_ip:
    static_ip: 192.168.2.103
    gateway: 192.168.2.1
    subnet: 255.255.255.0
    dns1: 192.168.2.1
    dns2: 8.8.8.8
